name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install ARCUS
        run: |
          # clone
          git clone https://github.com/naver/arcus.git $HOME/arcus
          
          # build server
          cd ~/arcus && docker compose up -d 

      - name: Test ARCUS Client Without ZK
        run: mvn clean verify -DUSE_ZK=false -Dtest=ObserverTest
      - name: Test ARCUS Client With ZK
        run: mvn clean verify -DUSE_ZK=true
