name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - develop
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: JDK ${{ matrix.jdk }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [ 8, 21 ]
        os: [ ubuntu-latest ]
      fail-fast: true
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install iproute2
        run: sudo apt-get install -y iproute2
      - name: Install ARCUS
        run: |
          # clone
          git clone https://github.com/naver/arcus.git $HOME/arcus

          # build server
          cd ~/arcus && docker compose up -d

      - name: Add 1ms localhost delay
        run: sudo tc qdisc add dev lo root netem delay 1ms
      - name: Test ARCUS Client Without ZK
        run: mvn clean verify -DUSE_ZK=false -Dtest=ObserverTest,ArcusClientCreateTest
      - name: Test ARCUS Client With ZK
        run: mvn clean verify -DUSE_ZK=true
